# Generated by Django 4.2.4 on 2023-09-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=20, unique=True)),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('mail', models.CharField(default='', max_length=30, unique=True)),
                ('phone', models.CharField(default='', max_length=20, unique=True)),
                ('fax', models.CharField(default='', max_length=20, unique=True)),
                ('website', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('year', models.CharField(default='', max_length=30, unique=True)),
                ('amount', models.CharField(default='', max_length=30, unique=True)),
                ('Dividend_type', models.CharField(default='', max_length=30, unique=True)),
                ('Ex_date', models.CharField(default='', max_length=30, unique=True)),
                ('Payment_date', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key_figures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('year', models.CharField(default='', max_length=30, unique=True)),
                ('Consolidated_accounts', models.CharField(default='', max_length=30, unique=True)),
                ('Share_capital', models.CharField(default='', max_length=30, unique=True)),
                ('Equity', models.CharField(default='', max_length=30, unique=True)),
                ('Number_of_titles', models.CharField(default='', max_length=30, unique=True)),
                ('Sales_figures', models.CharField(default='', max_length=30, unique=True)),
                ('Operating_result', models.CharField(default='', max_length=30, unique=True)),
                ('Net_income', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=20, unique=True)),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('post', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('year', models.CharField(default='', max_length=30, unique=True)),
                ('BPA', models.CharField(default='', max_length=30, unique=True)),
                ('ROE', models.CharField(default='', max_length=30, unique=True)),
                ('Payout', models.CharField(default='', max_length=30, unique=True)),
                ('Dividend_yield', models.CharField(default='', max_length=30, unique=True)),
                ('PER', models.CharField(default='', max_length=30, unique=True)),
                ('PBR', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='shareholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('holder', models.CharField(default='', max_length=20, unique=True)),
                ('pourcentage', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='Publications_page',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='instrument_link',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
