# Generated by Django 4.2.4 on 2023-09-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_contact_fax_alter_contact_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
    ]
