# Generated by Django 4.2.4 on 2023-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_dividend_amount_alter_dividend_dividend_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfigures',
            name='consolidated_accounts',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyfigures',
            name='equity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyfigures',
            name='net_income',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyfigures',
            name='number_of_titles',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyfigures',
            name='operating_result',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyfigures',
            name='sales_figures',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyfigures',
            name='share_capital',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyfigures',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
