# Generated by Django 4.2.4 on 2023-09-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_ratios_bpa_alter_ratios_dividend_yield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=1000)),
                ('doc_info', models.CharField(default='', max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
            ],
        ),
    ]
