# Generated by Django 4.2.4 on 2023-09-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=8, unique=True)),
                ('adress', models.CharField(max_length=50)),
                ('externalAuditor', models.CharField(max_length=50)),
                ('fiscalYearLength', models.IntegerField(default=1)),
                ('Creation_date', models.DateTimeField()),
                ('Ipo_date', models.DateTimeField()),
                ('Social_object', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
