# Generated by Django 4.2.4 on 2023-09-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_dividend_key_figures_management_ratios_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Dividend',
        ),
        migrations.DeleteModel(
            name='Key_figures',
        ),
        migrations.DeleteModel(
            name='Management',
        ),
        migrations.DeleteModel(
            name='Ratios',
        ),
        migrations.DeleteModel(
            name='shareholders',
        ),
    ]
