# Generated by Django 4.2.4 on 2023-09-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_company_delete_contact_delete_dividend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('external_auditor', models.CharField(max_length=50, null=True)),
                ('fiscal_year_length', models.IntegerField(default=1)),
                ('creation_date', models.DateField(default=None, null=True)),
                ('ipo_date', models.DateField(default=None, null=True)),
                ('social_object', models.CharField(max_length=1000, unique=True)),
                ('publications_page', models.CharField(default='', max_length=150)),
                ('instrument_link', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(default='', max_length=20, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=30, unique=True)),
                ('bpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('per', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pbr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('post', models.CharField(default='', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='KeyFigures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=30, unique=True)),
                ('consolidated_accounts', models.CharField(default='', max_length=30, unique=True)),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_titles', models.PositiveIntegerField(default=0)),
                ('sales_figures', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dividend_type', models.CharField(default='', max_length=30, unique=True)),
                ('ex_date', models.DateField(default=None, null=True)),
                ('payment_date', models.DateField(default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('mail', models.CharField(default='', max_length=30, unique=True)),
                ('phone', models.CharField(default='', max_length=20, unique=True)),
                ('fax', models.CharField(default='', max_length=20, unique=True)),
                ('website', models.CharField(default='', max_length=30, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
            ],
        ),
    ]
