# Generated by Django 4.2.4 on 2023-09-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
