# Generated by Django 4.2.4 on 2023-09-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_company_social_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='external_auditor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
