# Generated by Django 4.2.4 on 2023-09-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_company_social_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='name',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='post',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
