# Generated by Django 4.2.4 on 2023-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_keyfigures_consolidated_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratios',
            name='bpa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratios',
            name='dividend_yield',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratios',
            name='payout',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratios',
            name='pbr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratios',
            name='per',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratios',
            name='roe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ratios',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
